### PR TITLE
add failing test for keyword literal

### PR DESCRIPTION
**Pull request by novaugust**

### CODE REVIEW

**Review by doorgan — APPROVED** [review]
Thanks for this! This is a bug in core Elixir, I sent a PR to fix it https://github.com/elixir-lang/elixir/pull/11431

I'll update Sourceror accordingly once that one is merged

**Comment by novaugust** [comment]
<3 <3 thanks for all the help. if i run my local version of sourceror w/ elixir main i'll be able to get past this yeah? might be the last blocker on a big codebase rewrite =) cheers doorgan!

**Comment by doorgan** [comment]
@novaugust it should work, yes. I'll update Sourceror shortly though, now that my PR to Elixir was updated, and I'll release a new 0.8.x version

**Comment by doorgan** [comment]
For versions >= 1.13, Sourceror uses the builtin Elixir formatter functionality, but for <1.13 it uses a vendored version, which is why I have to backport every fix to Elixir to Sourceror too

**Comment by doorgan** [comment]
And done, v0.8.9 is out with both of the last fixed :)
Let me know how it goes!

**Pull request merged**
